# Generated by Django 4.2.13 on 2024-07-02 14:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя автора")),
                (
                    "surname",
                    models.CharField(max_length=100, verbose_name="Фамилия автора"),
                ),
                ("biography", models.TextField(verbose_name="Биография автора")),
            ],
        ),
    ]
