version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres:/data/postgres
    env_file:
      - ./.env

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_HOST=${MONGO_DB_HOST}
    volumes:
      - ${PWD}/_data/mongo:/data/db
      - ${PWD}/docker/_mongo/fixtures:/import
      - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/my_library
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo