# Generated by Django 4.2.13 on 2024-07-02 14:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название книги"),
                ),
                ("author", models.CharField(max_length=100, verbose_name="Автор")),
                ("description", models.TextField(verbose_name="Описание книги")),
                (
                    "year_of_publishing",
                    models.PositiveIntegerField(verbose_name="Год издания"),
                ),
            ],
        ),
    ]
