# Generated by Django 4.2.13 on 2024-07-02 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
    ]
